
# Hello and `welcome`

## PROVitD Group

This book contains information needed by a new comer in the  [PROVitD Group](https://www.igbmc.fr/equipes/sous-groupes/roles-physiopathologiques-des-voies-de-signalisation-de-la-vitamine-d) regarding data management in the lab, use of this gitlab, ressources on bioinformatics topics...

## Cheat Sheet

You can also follow the links to various cheat sheets and print them out to decorate your desk:

- [R](https://rstudio.github.io/cheatsheets/): to discover R universe
  - [Base R](https://rstudio.github.io/cheatsheets/base-r.pdf): to get started with R
  - [RStudio](https://rstudio.github.io/cheatsheets/html/rstudio-ide.html): to get started with RStudio
  - [R Best Practice](https://rstudio.github.io/cheatsheets/R-best-practice.pdf): to improve your R skills 
  - [ggplot2](https://rstudio.github.io/cheatsheets/html/data-visualization.html): to get started with generating plots
  - [dplyr](https://rstudio.github.io/cheatsheets/html/data-transformation.html): to manipulate datatables
  - [tidyr](https://rstudio.github.io/cheatsheets/html/tidyr.html): to tidy datatables
  - [quarto](https://rstudio.github.io/cheatsheets/html/quarto.html): to create beautiful notebooks with integrated code
  - [rmarkdown](https://rstudio.github.io/cheatsheets/html/rmarkdown.html): to create beautiful notebooks with integrated code (deprecated)
- [git](https://about.gitlab.com/images/press/git-cheat-sheet.pdf): to version control code
  - [git branching model](https://nvie.com/posts/a-successful-git-branching-model/): to develop tools with version control
- [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/cheatsheet.html): to use contained and reproducible package environment 

